repos:
  - repo: local
    hooks:
      - id: make-all
        name: Run make all
        entry: make all
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
