name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint
        run: uv run make lint

      - name: Type check
        run: uv run make type-check

      # - name: Run tests
      #   run: uv run make test
